### ISSUE TITLE
图表目录行距不一

### ISSUE THREAD

**Issue by prong879** [pasteller/njusttt#3]
您好！我发现图表目录中各行之间有空行，各行行距不一致，这个问题是什么原因引起的呀？如何让图表目录各行行距一致呢？

![image](https://github.com/user-attachments/assets/f1686373-36d2-4411-802e-eecbde9eebfd)

**Comment by pasteller** [comment]
> 您好！我发现图表目录中各行之间有空行，各行行距不一致，这个问题是什么原因引起的呀？如何让图表目录各行行距一致呢？
> 
> ![image](https://private-user-images.githubusercontent.com/100744303/374411213-f1686373-36d2-4411-802e-eecbde9eebfd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzOTQ5OTgsIm5iZiI6MTcyODM5NDY5OCwicGF0aCI6Ii8xMDA3NDQzMDMvMzc0NDExMjEzLWYxNjg2MzczLTM2ZDItNDQxMS04MDJlLWVlY2JkZTllZWJmZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwOFQxMzM4MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02Nzg0NWE3ZWVmN2Y3ODFiYTMyYTBmMzBmMmIxM2RiMmNkOWRhNDRhYmQzZTE1YjVkZDk3NjQ1Y2RhNzUzOWQ5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.WbkKFJyQzFWfRhAQZrnTIqKZ0hWEkZRiSkO_fc5aurI)

您好，图表目录里面图目录和表目录之间是间隔开的。同时，不同大章节之间的图表目录也会间隔一定行距。例如这张图中，表4.1和表5.1分属第四章和第五章，所以之间有间隔。如果想修改的话，可以在njusttt.cls中修改listoffiguresandtables函数。
