### ISSUE TITLE
参考文献引用的数字怎么不上标

### ISSUE THREAD

**Issue by tttsss-01** [pasteller/njusttt#4]
像是这样：
详见文献[1]

**Comment by SaqibMamoon** [comment]
When using TeXstudio or TeXmaker to compile your project, you have add both XeLatex and Biber as default compile setting as follows:

TeXstudio > Options >Configure TeXstudio >Build >Default Compiler > Click Configure icon and make following changes

![Weixin Image_20241125213653](https://github.com/user-attachments/assets/20226313-0ee1-4042-b447-86d906e7c3a0)

**Comment by pasteller** [comment]
> 像是这样： 详见文献[1]

You may try this command: \parencite{}

可以用\parencite{}替代\cite{}
