### ISSUE TITLE
关于宋体加粗

### ISSUE THREAD

**Issue by Outlying3720** [pasteller/njusttt#5]
注意到附录页面的宋体加粗和别处不大一样
![image](https://github.com/user-attachments/assets/55245bbc-bb8a-47ef-b53d-b732d4e00ed4)
现在的使用`\songti\zihao{4}\bf`是用simsun-bold字体
而改成`\songbf\zihao{4}`后是和别的标题加粗一样，调用AutoFakeBold的加粗

**Comment by pasteller** [comment]
> 注意到附录页面的宋体加粗和别处不大一样 ![image](https://private-user-images.githubusercontent.com/8683628/396338931-55245bbc-bb8a-47ef-b53d-b732d4e00ed4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0MzQzMTksIm5iZiI6MTczNDQzNDAxOSwicGF0aCI6Ii84NjgzNjI4LzM5NjMzODkzMS01NTI0NWJiYy1iYjhhLTQ3ZWYtYjUzZC1iNzMyZDRlMDBlZDQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMTdUMTExMzM5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDNkOTI3YmQ0OGUzZWZiYTEwNjBhZWMwN2M4ZWE5YjY4NmViNTFhYjIxMmM0OGVhM2QxYzhhODU1MGE2MmRlOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.uo7zxYmZNENAhZGsR3Jx4WUYFaQpMV5LzJxleL1PyAQ) 现在的使用`\songti\zihao{4}\bf`是用simsun-bold字体 而改成`\songbf\zihao{4}`后是和别的标题加粗一样，调用AutoFakeBold的加粗

确实不同。但出现这个问题的原因是\bf会将字体转为roman family。而\songbf用的\bfseries调用的AutoFakeBold加粗，所以字体没有变化。感谢指出，后面会把这个改为\songbf。
